/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStudentsUserIdRouteImport } from './routes/admin.students.$userId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsUserIdRoute = AdminStudentsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/companion': typeof CompanionRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/students/$userId': typeof AdminStudentsUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/companion': typeof CompanionRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/students/$userId': typeof AdminStudentsUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/companion': typeof CompanionRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/students/$userId': typeof AdminStudentsUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/companion'
    | '/login'
    | '/profile'
    | '/admin/students'
    | '/admin/students/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/companion'
    | '/login'
    | '/profile'
    | '/admin/students'
    | '/admin/students/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/companion'
    | '/login'
    | '/profile'
    | '/admin/students'
    | '/admin/students/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompanionRoute: typeof CompanionRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$userId': {
      id: '/admin/students/$userId'
      path: '/$userId'
      fullPath: '/admin/students/$userId'
      preLoaderRoute: typeof AdminStudentsUserIdRouteImport
      parentRoute: typeof AdminStudentsRoute
    }
  }
}

interface AdminStudentsRouteChildren {
  AdminStudentsUserIdRoute: typeof AdminStudentsUserIdRoute
}

const AdminStudentsRouteChildren: AdminStudentsRouteChildren = {
  AdminStudentsUserIdRoute: AdminStudentsUserIdRoute,
}

const AdminStudentsRouteWithChildren = AdminStudentsRoute._addFileChildren(
  AdminStudentsRouteChildren,
)

interface AdminRouteChildren {
  AdminStudentsRoute: typeof AdminStudentsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStudentsRoute: AdminStudentsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompanionRoute: CompanionRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
