/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StageRouteImport } from './routes/stage'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanionKioskRouteImport } from './routes/companion.kiosk'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStudentsUserIdRouteImport } from './routes/admin.students.$userId'

const StageRoute = StageRouteImport.update({
  id: '/stage',
  path: '/stage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionKioskRoute = CompanionKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => CompanionRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsUserIdRoute = AdminStudentsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/companion': typeof CompanionRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/stage': typeof StageRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/companion/kiosk': typeof CompanionKioskRoute
  '/admin/students/$userId': typeof AdminStudentsUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/companion': typeof CompanionRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/stage': typeof StageRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/companion/kiosk': typeof CompanionKioskRoute
  '/admin/students/$userId': typeof AdminStudentsUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/companion': typeof CompanionRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/stage': typeof StageRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/companion/kiosk': typeof CompanionKioskRoute
  '/admin/students/$userId': typeof AdminStudentsUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/companion'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/stage'
    | '/admin/students'
    | '/companion/kiosk'
    | '/admin/students/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/companion'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/stage'
    | '/admin/students'
    | '/companion/kiosk'
    | '/admin/students/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/companion'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/stage'
    | '/admin/students'
    | '/companion/kiosk'
    | '/admin/students/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompanionRoute: typeof CompanionRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  StageRoute: typeof StageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stage': {
      id: '/stage'
      path: '/stage'
      fullPath: '/stage'
      preLoaderRoute: typeof StageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion/kiosk': {
      id: '/companion/kiosk'
      path: '/kiosk'
      fullPath: '/companion/kiosk'
      preLoaderRoute: typeof CompanionKioskRouteImport
      parentRoute: typeof CompanionRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$userId': {
      id: '/admin/students/$userId'
      path: '/$userId'
      fullPath: '/admin/students/$userId'
      preLoaderRoute: typeof AdminStudentsUserIdRouteImport
      parentRoute: typeof AdminStudentsRoute
    }
  }
}

interface AdminStudentsRouteChildren {
  AdminStudentsUserIdRoute: typeof AdminStudentsUserIdRoute
}

const AdminStudentsRouteChildren: AdminStudentsRouteChildren = {
  AdminStudentsUserIdRoute: AdminStudentsUserIdRoute,
}

const AdminStudentsRouteWithChildren = AdminStudentsRoute._addFileChildren(
  AdminStudentsRouteChildren,
)

interface AdminRouteChildren {
  AdminStudentsRoute: typeof AdminStudentsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStudentsRoute: AdminStudentsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CompanionRouteChildren {
  CompanionKioskRoute: typeof CompanionKioskRoute
}

const CompanionRouteChildren: CompanionRouteChildren = {
  CompanionKioskRoute: CompanionKioskRoute,
}

const CompanionRouteWithChildren = CompanionRoute._addFileChildren(
  CompanionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompanionRoute: CompanionRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  StageRoute: StageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
